application: aesc
version: 1
runtime: python
api_version: 1

default_expiration: "1d"

handlers:
  - url: /favicon.ico
    static_files: static/images/favicon.ico
    upload: static/images/favicon.ico
    login: required
  
  - url: /static/images/fileicons/.*
    script: zip_handler.py
    login: required
    
  - url: /fckeditor/.*
    script: zip_handler.py
    login: required
  
  - url: /static
    static_dir: static
    login: required

  - url: /.*
    script: main.py
    login: required
